うまく表示できず
traP-jp/h23s_26-UI pull request #14
Opened 2023-06-17 06:09 UTC by mizoreyuki8

2023-06-17 06:23 UTC, cp-20 commented
うまく表示できないとは具体的にどういう意味ですか？ (スクショなどがあるとわかりやすいかもです)

2023-06-17 06:26 UTC, cp-20 requested changes

2023-06-17 06:26 UTC, cp-20 commented on src/pages/dashboard.tsx
> +  return <Avatar size="20" src="avater.pig" />;
アバターのスペルは`avatar`ですね。ついでに画像の拡張子は`.png`だと思います。

2023-06-17 06:28 UTC, cp-20 commented on src/pages/dashboard.tsx
> +          place-content: center;
全体が縮まっちゃうのはこのあたりの`display: grid;`と`place-content: center;`が原因ですね

2023-06-17 06:35 UTC, mizoreyuki8 commented
display:grid;とplace-content:center;で一番上のものの大きさにそろっちゃってる感じか

2023-06-17 15:54 UTC, mizoreyuki8 commented
<img width="1440" alt="スクリーンショット 2023-06-18 0 52 07" src="https://github.com/traP-jp/h23s_26-UI/assets/105897071/be4b15cd-f185-47f8-b1d5-a73521f36588">
・アイコンの下にアカウント名出したい
・円グラフとタイトルを綺麗に並べたい
・グラフと順位をもっといい感じに離したい
・40%と50をもっと大きくしたい

2023-06-18 05:52 UTC, cp-20 approved these changes

2023-06-18 06:34 UTC, merged